In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os.path
import platform

from ch07.Covid_data_1024 import kor_data

In [17]:
df_raw = pd.read_csv('data/hawaii-covid-data.csv', encoding='cp949')
df_raw.head()

,submission_date,state,tot_cases,conf_cases,prob_cases,new_case,pnew_case,tot_death,conf_death,prob_death,new_death,pnew_death,created_at,consent_cases,consent_deaths
0,10/26/2021,HI,80876,NaN,NaN,69,10.0,883,NaN,NaN,0,0.0,10/27/2021 02:21:35 PM,Not agree,Not agree
1,06/17/2021,HI,35862,NaN,NaN,31,0.0,504,NaN,NaN,0,0.0,06/18/2021 01:48:26 PM,Not agree,Not agree
2,12/30/2021,HI,106350,NaN,NaN,3425,368.0,1074,NaN,NaN,0,0.0,12/31/2021 02:32:16 PM,Not agree,Not agree
3,11/12/2020,HI,16171,NaN,NaN,94,0.0,221,NaN,NaN,0,0.0,11/13/2020 02:54:34 PM,Not agree,Not agree
4,06/15/2021,HI,35802,NaN,NaN,33,5.0,503,NaN,NaN,0,0.0,06/16/2021 03:10:20 PM,Not agree,Not agree

In [6]:
kor_data = pd.read_csv('../ch05/data/covid-kor.csv', encoding='cp949')
kor_data.head()

         date iso_code     location  total_cases  population
0  2020-01-05      KOR  South Korea          0.0    51815808
1  2020-01-06      KOR  South Korea          0.0    51815808
2  2020-01-07      KOR  South Korea          0.0    51815808
3  2020-01-08      KOR  South Korea          0.0    51815808
4  2020-01-09      KOR  South Korea          0.0    51815808

In [11]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   submission_date  912 non-null    object
 1   state            912 non-null    object
 2   tot_cases        912 non-null    int64
 3   conf_cases       0 non-null      float64
 4   prob_cases       0 non-null      float64
 5   new_case         912 non-null    int64
 6   pnew_case        869 non-null    float64
 7   tot_death        912 non-null    int64
 8   conf_death       0 non-null      float64
 9   prob_death       0 non-null      float64
 10  new_death        912 non-null    int64
 11  pnew_death       823 non-null    float64
 12  created_at       912 non-null    object
 13  consent_cases    912 non-null    object
 14  consent_deaths   912 non-null    object
dtypes: float64(6), int64(4), object(5)
memory usage: 107.0+ KB

In [12]:
col = ['date', 'ios_code', 'total_cases', 'population']
# df_raw 에 population 열 추가
df_raw['population'] = 0
hi_data = df_raw[['submission_date','state','tot_cases','population']]
hi_data.head()
hi_data

    submission_date state  tot_cases  population
0        10/26/2021    HI      80876           0
1        06/17/2021    HI      35862           0
2        12/30/2021    HI     106350           0
3        11/12/2020    HI      16171           0
4        06/15/2021    HI      35802           0
..              ...   ...        ...         ...
907      08/22/2021    HI      54038           0
908      04/16/2020    HI        544           0
909      05/23/2021    HI      34654           0
910      09/07/2021    HI      66554           0
911      09/17/2021    HI      72137           0

[912 rows x 4 columns]

In [23]:
# 하와이 인구수 2021년 기준
df_raw['population'] = 1441553

# 문자열 포멧을 날짜 포멧으로 바꿈
df_raw['date'] = pd.to_datetime(df_raw['submission_date'])
df_raw_filter = df_raw[['date', 'tot_cases', 'population']]

df_raw_filter.set_index('date', inplace=True) # inplace=True 는 기본 데이터를 냅두고 가공한 데이터를 따로 가져가는 느낌인듯, 따론 변수 선언 안해도 됨

df_raw_filter.head()

            tot_cases  population
date
2021-10-26      80876     1441553
2021-06-17      35862     1441553
2021-12-30     106350     1441553
2020-11-12      16171     1441553
2021-06-15      35802     1441553

In [24]:
import os
kor_covid_csv_file_path = 'data/covid-hawai.csv'
if os.path.exists(kor_covid_csv_file_path):
    os.remove(kor_covid_csv_file_path)
df_raw_filter.to_csv(kor_covid_csv_file_path)